[package]
name = "project"
version = "0.1.0"
authors = ["ariolandi <stela_marinova@abv.bg>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.5"
simple-matrix = "0.1"
termion = "1"
